# background #1A1A1A
background #151515
foreground #C8C8C8
cursor #CBAA88
url_color #D4CDEB
selection_background #323232
selection_foreground #C8C8C8
color0  #1A1A1A
color8  #5B5B5B
color1  #D59192
color9  #FFBCBD
color2  #B3B393
color10  #DFDFBE
color3  #BFAF8E
color11  #ECDBB9
color4  #A8A1BE
color12  #D4CDEB
color5  #B99BB5
color13  #E6C6E1
color6  #A8A1BE
color14  #D4CDEB
color7  #5B5B5B
color15  #5B5B5B
