background #242933
foreground #BBC3D4
cursor #191D24
url_color #5E81AC
selection_background #222630
selection_foreground #BBC3D4
color0  #191D24
color8  #3B4252
color1  #BF616A
color9  #C5727A
color2  #A3BE8C
color10  #B1C89D
color3  #EBCB8B
color11  #EFD49F
color4  #5E81AC
color12  #88C0D0
color5  #B48EAD
color13  #BE9DB8
color6  #8FBCBB
color14  #9FC6C5
color7  #BBC3D4
color15  #D8DEE9
